const data=[
  ["Amara's Beauty Studio",['Hair','Nails'],'Bonamoussadi, Douala','At provider',4.9,5000,'/nails.jpeg'],
  ["Glow by Nella",['Makeup','Lashes & Brows'],'Molyko, Buea','Both',4.8,7000,'/Makeup.jpeg'],
  ["Gentleman's Cut",['Barbering'],'Akwa, Douala','At provider',4.9,4000,"/Gentleman's Cut.jpeg"],
  ['The Nail Room',['Nails'],'Buea Town, Buea','Home service',4.7,6000,'/nails.jpeg'],
  ['Luxe Face Studio',['Makeup','Lashes & Brows'],'Bonapriso, Douala','Both',4.9,10000,'/Makeup.jpeg'],
  ['Crown & Coils',['Hair'],'Molyko, Buea','Home service',4.6,5500,'/nails.jpeg'],
  ['Serenity Spa',['Spa & Skincare'],'Bonanjo, Douala','At provider',4.8,12000,'/Makeup.jpeg'],
  ['Fresh Fade Studio',['Barbering'],'Molyko, Buea','Both',4.5,3500,"/Gentleman's Cut.jpeg"],
  ['Soft Glow Beauty',['Hair','Makeup'],'Bepanda, Douala','At provider',4.7,8000,'/Makeup.jpeg']
];
const grid=document.querySelector('#grid');function render(){let q=document.querySelector('#q').value.toLowerCase(),
  l=document.querySelector('#loc').value.toLowerCase(),cats=[...document.querySelectorAll('.cat:checked')].map(x=>x.value),
  types=[...document.querySelectorAll('.type:checked')].map(x=>x.value),r=+document.querySelector('input[name=rating]:checked')?.value||0;
                                                             let a=data.filter(x=>(!q||(x[0]+' '+x[1].join(' ')).toLowerCase().includes(q))&&(!l||x[2].toLowerCase().includes(l))&&(!cats.length||cats.some(c=>x[1].includes(c)))&&(!types.length||types.includes(x[3]))&&x[4]>=r);const s=document.querySelector('#sort').value;if(s==='rating')a.sort((x,y)=>y[4]-x[4]);if(s==='low')a.sort((x,y)=>x[5]-y[5]);if(s==='high')a.sort((x,y)=>y[5]-x[5]);document.querySelector('#count').textContent=a.length+' professionals available';document.querySelector('#heading').textContent=l?'Professionals in '+document.querySelector('#loc').value:'Professionals near you';
                                                             grid.innerHTML=a.map(x=>`<article class="card"><div class="card-img" style="height:200px;overflow:hidden;"><img src="${x[6]}" alt="${x[0]}" style=width:100%;height:100%;object-fit:cover;border-radius:12px 12px 0 0;"></div><div class="card-body">`
                                                             <h3>${x[0]}</h3><p>${x[2]}</p><div class="tags">${x[1].map(t=>`<span>${t}</span>`).join('')}<span>${x[3]}</span></div>
                                                             <div class="meta"><span>From ${x[5].toLocaleString()} FCFA<br><b class="rating">★ ${x[4]}</b></span>
                                                             <a href="provider.html?name=${encodeURIComponent(x[0])}">View profile →</a></div></div></article>`).join('')}document.querySelector('#searchForm').onsubmit=e=>{e.preventDefault();render()};document.querySelector('#sort').onchange=render;document.querySelector('#clear').onclick=()=>{document.querySelectorAll('input').forEach(x=>x.checked=false);q.value='';loc.value='';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  render()};const u=new URLSearchParams(location.search);if(u.get('service'))q.value=u.get('service');if(u.get('location'))loc.value=u.get('location');if(u.get('category')){const m={hair:'Hair',nails:'Nails',makeup:'Makeup',barbering:'Barbering','lashes-brows':'Lashes & Brows',spa:'Spa & Skincare'};const c=[...document.querySelectorAll('.cat')].find(x=>x.value===m[u.get('category')]);if(c)c.checked=true}render();
